### PR TITLE
added starter code for html

### PR DESCRIPTION
**Pull request by McLee0218**

### CODE REVIEW

**Review by MadeOfBees — COMMENTED** [review]
These changes are all behind the current branch, did you git pull origin main before working?

**Comment by McLee0218** [comment]
I though I git pull before, my apologies, however I thought the starter code has to be added before other information is added.

**Comment by McLee0218** [comment]
conflict resolved, please approve.

**Comment by MadeOfBees** [comment]
We pushed bootstrap up to main a few minutes ago so this is now behind main

**Pull request closed without merging**
